@baseUrl = http://127.0.0.1:1880

###
@authToken = {{signIn.response.body.token}}

###
# @name signIn
POST {{baseUrl}}/sign-in/
content-type: application/json

{
    "login": "leo",
    "password": "0987654321"
}

###
# @name getDeviceState
GET {{baseUrl}}/api/states/device/1
Authorization: Bearer {{authToken}}

###
# @name getDeviceStatesByDateRange
GET {{baseUrl}}/api/states/device/1/dates?beginDate=2025-10-31T00:00:00&endDate=2025-10-31T23:59:59
Authorization: Bearer {{authToken}}

###
# @name postDeviceStateValue
POST {{baseUrl}}/api/states/3  HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "address": 7,
    "value": true
}

###
# @name getDevices
GET {{baseUrl}}/api/devices
Authorization: Bearer {{authToken}}

###
# @name getFlows
GET {{baseUrl}}/api/flows
Authorization: Bearer {{authToken}}

###
# @name getMnemoschema
GET {{baseUrl}}/api/mnemoschemas/device/1
Authorization: Bearer {{authToken}}
