GET http://127.0.0.1:1880/api/get-state/1

###
GET http://127.0.0.1:1880/api/get-states-by-dates/1?beginDate=2025-10-31T00:00:00&endDate=2025-10-31T23:59:59

###
POST http://127.0.0.1:1880/api/set-state/3  HTTP/1.1
content-type: application/json

{
    "address": 7,
    "value": true
}

###
GET http://127.0.0.1:1880/api/get-devices
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVJZCI6MSwiaWF0IjoxNzYyNzUzMzYzLCJleHAiOjE3NjI4Mzk3NjN9.Yq6tRURCsh85eR1eKHbC-uHt2OLQO1thkesSgiBcymo

###
GET http://127.0.0.1:1880/api/get-mnemoschema/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGVJZCI6MSwiaWF0IjoxNzYyNzUzMzYzLCJleHAiOjE3NjI4Mzk3NjN9.Yq6tRURCsh85eR1eKHbC-uHt2OLQO1thkesSgiBcymo

###
POST  http://127.0.0.1:1880/sign-in/
content-type: application/json

{
    "login": "leo",
    "password": "0987654321"
}
